### PR TITLE
Mark valign-mode as autoload

### PR DESCRIPTION
**Pull request by ksqsf**
I mean, why not? ;-)

### CODE REVIEW

**Comment by ksqsf** [comment]
so I noticed your use of `:require`. but to my understanding this is useless, cuz you have to load valign.el first for emacs to note that you can load valign.el for valign-mode.

use the autoload annotation (+ update-file-autoloads) can properly set up autoloading.

**Comment by casouri** [comment]
Hmmm, what do you mean by `:require`?

**Comment by ksqsf** [comment]
oh, I misread the doc. 

```
:require
	VALUE should be a feature symbol.  If you save a value
	for this option, then when your init file loads the value,
	it does (require VALUE) first.
```

anyway it is not autoload...

**Comment by casouri** [comment]
I still don't understand, which part of the code are you referring to?

**Comment by casouri** [comment]
Ah, you mean `valign-mode`. I didn't add it, tumashu did. As for autoload, we are not distributing valign.el through package.el so that doens't do anything now. I'll add it if valign.el goes into ELPA/MELPA.

**Comment by casouri** [comment]
Or if you can format the commit message in standard Emacs style (See CONTRIBUTE in Emacs source), I'm happy to merge it.

**Comment by ksqsf** [comment]
> so that doens't do anything now

it does. e.g. I can use `update-file-autoloads` to generate autoload calls.

> if you can format the commit message in standard Emacs style

done.

**Comment by casouri** [comment]
Thanks.

**Pull request merged**
